### ISSUE TITLE
Add tests to the test suite

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/blm-corpus#11]
Check that it is 594 editions
Check that there are no obvious duplicates in text and metadata

**Comment by MansMeg** [comment]
Ok. Alexandra said that it should be 594. The question is who is wrong. :)

**Comment by emla5688** [comment]
Either way, the code is done, and can easily be changed such that it corresponds to the correct number of pages

**Comment by MansMeg** [comment]
Great! But please check with Alexandra so we have all editions.
