### ISSUE TITLE
Add designer information to the metadata

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/blm-corpus#20]
Alexandra should have an excel file with the information on the designers.

Ideally we should have two csv-files in the metadata:

designers.csv with information:
person_id;wikidata_id

person_id, I suggest we just use uuid, look up if we can get wikidata id för these person (probably easiest to do manually) and add. 
maybe alexand has additional information on these persons in her file that also could be added.

Then create designed_by.csv with information:
person_id;blm_edition_id

Ie that maps the edition of the designer to the BLM id (Im not sure what id to use, but probably the dark... KB id. The file should have as many lines as you have editions is my guess.

**Comment by emla5688** [comment]
I got the list of graphic designers from Alexandra, but she does not currently have the specific years. I found that 9 out of 17 exist on wikidata

**Comment by emla5688** [comment]
Yes, I just received an email including some of the years and designers

**Comment by MansMeg** [comment]
Ok. Then wait until Alexandra is done with her work, and then we will add it.

**Comment by emla5688** [comment]
Okay, great!

**Comment by MansMeg** [comment]
No. Just add one additional row. So in designed_by.csv:
person_id;blm_edition_id
designer_1;blm_edition_1
designer_2;blm_edition_1

Do you have information on the parts that they designed, add that as a column:
person_id;blm_edition_id;part
designer_1;blm_edition_1;cover
designer_2;blm_edition_1;layout


Does this make sense?

**Comment by emla5688** [comment]
Yeah, I do have that information. Sounds good!

**Comment by emla5688** [comment]
I have now done most of the work, however, there are some overlaps in time for different designers, for example: designer x (1991-1992) and then designer y (1992-1996). As far as I know there is not a way to assess which designer was responsible for which editions.

**Comment by MansMeg** [comment]
Ok. Then you can either just add start year and end year in designers.csv as two columns and skip the designed_by.csv file.

Alternatively, you can add all editions during the years in the designed_by.csv .

**Comment by emla5688** [comment]
All editions are added to the designed_by.csv, but should I add the specific date or year for each edition or just the start and end date or year for the designer for each corresponding edition?

**Comment by MansMeg** [comment]
So we could extract the dates from the designed_by.csv? I guess that is sufficient, then we can extract that information later if needed? Right?

**Comment by emla5688** [comment]
Yeah, cause then we could look at the time periods for the different designers, which I think will be useful.

**Comment by MansMeg** [comment]
Exact. Also this is good to have in the corpus but not crucial. So we get in what we have and then see if we need it later.

**Comment by emla5688** [comment]
Done!
