### ISSUE TITLE
Minor issues to fix after demonstration

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/blm-corpus#26]
- [x] Fix the documentation of the functions and the arguments with docstrings. Look up docstrings for Python. this will formate the documentation correctly. 
- [x] Document all arguments in the Python functions (i.e. what goes in and what goes out)
- [ ] Change title to edition ID to clarify
- [x] Compute no of words per page and headers per page as a function instead of data in the XML page (i.e. remove this from the XML).
- [x] Move unit tests to a root/test folder instead.
- [x] Add the name of the designers to the csv document
- [x] change the metadata.csv file name to edition.csv
- [x] in design_by.csv change ID to edition_id.
- [x] Sort metadata.csv deterministically, ie by edition_id

When all these small things are done. Do a new release.

**Comment by magan6** [comment]
Regarding "Change title to edition ID to clarify"

The Title is something that is made and defined when the Epub is constructed. That's why it is a part of the xhtml file.
_pub.EpubHtml(**title**=id, file_name="content.xhtml", lang="sv")_

It can be removed, but the name for this is default.

**Comment by MansMeg** [comment]
Ah. Then leave this for now.
