### ISSUE TITLE
Add page numbers to all pages

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/blm-corpus#28]
The page number in BLM is not extracted from the pages. This should be done so the numbers can both be removed in the analysis and that they can be used as metadata.

**Comment by emla5688** [comment]
We went through numerous pages and found that in many cases the page numbers are not part of the alto.xml-files on the API. We will see if it is improved/fixed with the new versions of the OCR.

**Comment by MansMeg** [comment]
Great! Yes, then just leave this issue open.

**Comment by liamtabib** [comment]
Done.
