### ISSUE TITLE
Unit test that all ids are unique

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/blm-corpus#29]
We should check that the ids in the corpus like edition_id is unique

**Comment by emla5688** [comment]
I have previously constructed a test which checks that all edition-id's in the corpus-folder exist in our edition.csv and that there are no duplicates in either one. Is this what you meant?

**Comment by MansMeg** [comment]
Yes. So this is done then?

**Comment by emla5688** [comment]
Yes!
