### ISSUE TITLE
Create a blm-corpus-supplementary-material repo

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/blm-corpus#31]
We should create a private repository where we can store raw data we use in the processing of the blm files. 

Im not sure if we should have it on kblab only or also on github.

**Comment by liamtabib** [comment]
Should the quality control directory, which contains both gold standard datasets and accuracy scripts (for ocr estimation and segmentation accuracy) also be moved to this repo?

**Comment by MansMeg** [comment]
No. We should keep everything we need for quality control and estimation in the original repo in a quality or so folder (see the SWERIK corpus).

**Comment by liamtabib** [comment]
Okay, should we create /input where we store gold standards and manual annotations?

**Comment by MansMeg** [comment]
I would create a folder called ”technical/quality/ocr_quality” for the ocr gold standard eg. It is not clear exact what we want to do in swerik.

**Comment by liamtabib** [comment]
technical directory is created
