### ISSUE TITLE
Create a mapping between article ids and the table of contents files

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/blm-corpus#32]
We want to create a mapping between the registers/table of contents and the article ids.

I think each unique article in BLM has an article ID. We want to create a new csv-file mapping each element of the registers to an article id.

**Comment by liamtabib** [comment]
What purpose will the table of contents/registers serve?

**Comment by MansMeg** [comment]
So the registers/table of content file contain information on which articles (here seen as article IDs) are of which type. So if we can map these files to article IDs (first just programmatically) we get information on which article IDs are "bokrecentioner". Does that make sense?

**Comment by liamtabib** [comment]
Yes!

**Comment by liamtabib** [comment]
Done.
