### ISSUE TITLE
Add true page for editions to metadata

### ISSUE THREAD

**Issue by liamtabib** [welfare-state-analytics/blm-corpus#35]
Each edition in our corpus starts with page 1, but in truth the pagination is year based- i.e. if the _january_ edition ends in page 50, the _february_ edition starts with page 51. This is not included in our corpus.

Inside _toc.csv_, the column that contains the page number is in the latter format- on year basis. So in order to utilise this information,  we should add what the true start page and true last page is for each edition, possibly by adding two columns to _editions.csv_, named _true_start_page_ and _true_end_page_.

Suggestions?

**Comment by liamtabib** [comment]
This is more cumbersome than expected, since the pagination does not start on the first page, and does not end on the last page. Hence mapping our pagination with the true pagination would require segmentation of page numbers.

**Comment by liamtabib** [comment]
true_page is now an attribute to <pb> tag

**Comment by MansMeg** [comment]
Did you solve the problem? Great work!

**Comment by liamtabib** [comment]
Yes, although as per feedback from Väinö I will wrap around the page number inside its own tag in the xml.
