### ISSUE TITLE
Create a metadata file on editions

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/blm-corpus#5]
We should create a metadata csv file that maps the edition and year to the individual files/folders

**Comment by emla5688** [comment]
Completed

**Comment by MansMeg** [comment]
Cool! Is blm now released as v0.2 at kblab gitlab?

**Comment by MansMeg** [comment]
? Sorry. Dont understand? The issue is to create the csv-file, add it to the corpus in corpus/metadata/ and the release it as a new version of BLM?

**Comment by emla5688** [comment]
Now it's done.

**Comment by MansMeg** [comment]
Please close the issue if it has been released.
