### ISSUE TITLE
Add uuid for each page in the corpus

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/blm-corpus#9]
We need to be able to efficiently identify pages in the corpus (for manual annotation)

Hence, we need to add an id per page with uuid. Look at the riksdagen corpus for an example how this is added.

@ninpnin which lib in Python do you use for this?

**Comment by ninpnin** [comment]
Standard python uuid library. We also use another library to format that slightly shorter than the standard UUIDs, but that ultimately does not matter that much.

**Comment by magan6** [comment]
I have used the uuid library together with the random library and added uuid to all pages. The uuid:s are generated by a seed and will thereby be consistent for all new versions.
